version: "3.8"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "6669:6669"
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
