version: '3.8'
services:
  db:
    container_name: chorebot_db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chorebot_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data/
