[package]
name = "rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oauth2 = "4.1"
tokio = {version= "1.11", features = ["full"]}
reqwest = { version = "0.11", features = ["json"] }
