[package]
name = "rust"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "choretle"
path = "src/main.rs"

[dependencies]
tokio = {version = "1.11", features = ["full"]}
serenity = "0.10"
rand = "0.8.4"
reqwest = "0.11.4"
